name: Run Colab Notebook with Papermill

on:
  schedule:
    - cron: '0 5 * * *'  # Chạy vào 10h sáng UTC mỗi ngày

jobs:
  run_colab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install papermill nbformat
    - name: Install dependencies
      run: |
        pip install papermill nbformat ipykernel
        python -m ipykernel install --user --name python3
    - name: Run Notebook with Papermill
      run: |
        papermill Connect_Linkedin_with_cookie.ipynb your_output.ipynb
    - name: Commit and Push Output
      run: |
        git config --local user.email "donate@tahkfoundation.org"
        git config --local user.name "TAHKInteractingAI"
        git add your_output.ipynb
        git commit -m "Update output notebook"
        git push
