name: Run Colab Notebooks with Papermill

on:
  schedule:
    - cron: '0 2 * * *'  # Chạy vào 10h sáng UTC mỗi ngày

jobs:
  run_colab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install papermill nbformat ipykernel
        python -m ipykernel install --user --name python3

    - name: Run First Notebook with Papermill
      run: |
        papermill Connect_Linkedin_with_cookie.ipynb output_first_notebook.ipynb

    - name: Run Second Notebook with Papermill
      run: |
        papermill LINKEDIN_BOT_MESSAGE_V2.ipynb output_second_notebook.ipynb

    - name: Commit and push results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add *.ipynb
        git commit -m "Save notebook output [skip ci]"
        git push
