name: Run Colab Notebooks with Papermill

on:
  schedule:
    - cron: '0 2 * * *'  # Chạy vào 10h sáng UTC mỗi ngày

jobs:
  run_colab:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install papermill nbformat ipykernel
        python -m ipykernel install --user --name python3

    - name: Commit and push results
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add *.ipynb
        git commit -m "Save notebook output [skip ci]" || echo "No changes to commit"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}

